// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BeiAn: typeof import('./src/components/bei-an.vue')['default']
    BizHello: typeof import('./src/biz-components/biz-hello.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScrollDown: typeof import('./src/components/scroll-down.vue')['default']
    WelcomeSvg: typeof import('./src/components/welcome-svg.vue')['default']
  }
}

export {}
